# Generated by Django 4.2.8 on 2025-08-26 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('dnssec_enabled', models.BooleanField(default=False)),
                ('serial', models.BigIntegerField(default=1)),
                ('refresh', models.IntegerField(default=3600)),
                ('retry', models.IntegerField(default=1800)),
                ('expire', models.IntegerField(default=604800)),
                ('minimum', models.IntegerField(default=86400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dns_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('SOA', 'SOA'), ('PTR', 'PTR'), ('SRV', 'SRV')], max_length=10)),
                ('value', models.TextField()),
                ('ttl', models.IntegerField(default=3600)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dns.dnszone')),
            ],
            options={
                'db_table': 'dns_records',
                'ordering': ['zone', 'name', 'type'],
                'unique_together': {('zone', 'name', 'type', 'value')},
            },
        ),
    ]
