# Generated by Django 4.2.8 on 2025-08-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '__first__'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='asn',
            field=models.PositiveIntegerField(blank=True, help_text='Autonomous System Number', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='facility_id',
            field=models.CharField(blank=True, help_text='External facility reference', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='group',
            field=models.CharField(blank=True, choices=[('branch', 'Branch'), ('hq', 'HQ'), ('dc', 'Data Center'), ('corporate', 'Corporate'), ('remote', 'Remote')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='physical_address',
            field=models.TextField(blank=True, help_text='Physical location details'),
        ),
        migrations.AddField(
            model_name='site',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.CharField(blank=True, choices=[('americas', 'Americas'), ('emea', 'EMEA'), ('apac', 'APAC'), ('asia_pacific', 'Asia Pacific')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Shipping address if different'),
        ),
        migrations.AddField(
            model_name='site',
            name='state_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='site',
            name='time_zone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(help_text='Unique site identifier (e.g., NYC-01)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('staging', 'Staging'), ('decommissioning', 'Decommissioning'), ('retired', 'Retired')], db_index=True, default='planned', max_length=20),
        ),
    ]
