# Generated by Django 4.2.8 on 2025-08-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('threshold', 'Threshold'), ('status', 'Status Change'), ('pattern', 'Pattern Match'), ('availability', 'Availability')], max_length=20)),
                ('condition', models.JSONField(help_text='JSON condition for triggering alert')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('equipment_type', models.CharField(blank=True, help_text='Equipment type to apply rule to', max_length=100)),
                ('notification_channels', models.JSONField(default=list, help_text='List of notification channels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='sites.site')),
            ],
            options={
                'db_table': 'alert_rules',
                'ordering': ['name'],
            },
        ),
    ]
