# Generated by Django 4.2.8 on 2025-08-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('sites', '0001_initial'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderedconfig',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='renderedconfig',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='renderedconfig',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendered_configs', to='configurations.configtemplate'),
        ),
    ]
