# Generated by Django 4.2.8 on 2025-08-26 22:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cidr', models.CharField(max_length=43, unique=True)),
                ('vlan_id', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_servers', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subnets',
                'ordering': ['cidr'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('ASSIGNED', 'Assigned'), ('RESERVED', 'Reserved'), ('CONFLICT', 'Conflict')], default='FREE', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_assigned', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_allocations', to='equipment.equipment')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='equipment.interface')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='ipam.subnet')),
            ],
            options={
                'db_table': 'ip_addresses',
                'ordering': ['address'],
            },
        ),
        migrations.AddIndex(
            model_name='subnet',
            index=models.Index(fields=['cidr'], name='subnets_cidr_67eca1_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['address'], name='ip_addresse_address_6c9c77_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['mac_address'], name='ip_addresse_mac_add_b2befa_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['status'], name='ip_addresse_status_f2b7b7_idx'),
        ),
    ]
